Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@same'

Options:
 cppcheck-ignore-files:
  - autotests
 test-before-installing: True
 require-passing-tests-on: ['@all']
